package server
import "net/http"
func(s *Server)dashboard(w http.ResponseWriter,r *http.Request){w.Header().Set("Content-Type","text/html; charset=utf-8");w.Write([]byte(dashHTML))}
const dashHTML=`<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Semaphore</title>
<style>:root{--bg:#1a1410;--bg2:#241e18;--bg3:#2e261e;--rust:#c45d2c;--rl:#e8753a;--leather:#a0845c;--cream:#f0e6d3;--cm:#7a7060;--gold:#d4a843;--green:#4a9e5c;--mono:'JetBrains Mono',Consolas,monospace;--serif:'Libre Baskerville',Georgia,serif}*{margin:0;padding:0;box-sizing:border-box}body{background:var(--bg);color:var(--cream);font-family:var(--mono);font-size:13px;line-height:1.6}.hdr{padding:.6rem 1.2rem;border-bottom:1px solid var(--bg3);display:flex;justify-content:space-between;align-items:center}.hdr h1{font-family:var(--serif);font-size:1rem}.hdr h1 span{color:var(--rl)}.sub{font-size:.65rem;color:var(--cm)}.main{max-width:700px;margin:0 auto;padding:1rem}.search{width:100%;background:var(--bg2);border:1px solid var(--bg3);color:var(--cream);padding:.4rem .6rem;font-family:var(--mono);font-size:.78rem;margin-bottom:.6rem;outline:none}.search:focus{border-color:var(--rust)}.stats{display:flex;gap:1rem;margin-bottom:.8rem;flex-wrap:wrap}.stat{text-align:center}.stat-n{font-size:1.2rem;color:var(--rl);font-family:var(--serif)}.stat-l{font-size:.55rem;color:var(--cm);text-transform:uppercase;letter-spacing:1px}.btn{font-family:var(--mono);font-size:.68rem;padding:.3rem .6rem;border:1px solid;cursor:pointer;background:transparent}.btn-p{border-color:var(--rust);color:var(--rl)}.btn-p:hover{background:var(--rust);color:var(--cream)}.item{background:var(--bg2);border:1px solid var(--bg3);padding:.6rem;margin-bottom:.3rem;cursor:pointer;transition:border-color .15s}.item:hover{border-color:var(--leather)}.item h3{font-size:.82rem;margin-bottom:.15rem}.item-meta{font-size:.65rem;color:var(--cm);display:flex;gap:.5rem;flex-wrap:wrap}.empty{text-align:center;padding:2rem;color:var(--cm);font-style:italic;font-family:var(--serif)}.modal-bg{position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,.65);display:flex;align-items:center;justify-content:center;z-index:100}.modal{background:var(--bg2);border:1px solid var(--bg3);padding:1.5rem;width:90%;max-width:500px;max-height:90vh;overflow-y:auto}.modal h2{font-family:var(--serif);font-size:.9rem;margin-bottom:1rem}label.fl{display:block;font-size:.65rem;color:var(--leather);text-transform:uppercase;letter-spacing:1px;margin-bottom:.2rem;margin-top:.5rem}input[type=text],input[type=number]{background:var(--bg);border:1px solid var(--bg3);color:var(--cream);padding:.35rem .5rem;font-family:var(--mono);font-size:.78rem;width:100%;outline:none}.del{color:var(--cm);cursor:pointer;font-size:.65rem;float:right}.del:hover{color:var(--rust)}</style></head>
<body><div class="hdr"><div><h1><span>Stockyard</span> Semaphore</h1><div class="sub">Self-hosted team availability board</div></div><button class="btn btn-p" onclick="showModal()">+ New</button></div>
<div class="main"><div class="stats" id="stats"></div>
<input class="search" id="search" placeholder="Search team_members..." oninput="debounceSearch()">
<div id="list"></div></div>
<div class="modal-bg" id="modal" style="display:none" onclick="if(event.target===this)hideModal()"><div class="modal"><h2 id="mt">New TeamMember</h2>
<label class="fl">Name</label><input type="text" id="f-name" placeholder="Name"><label class="fl">Email</label><input type="text" id="f-email" placeholder="Email"><label class="fl">Role</label><input type="text" id="f-role" placeholder="Role"><label class="fl">Availability</label><input type="text" id="f-availability" placeholder="Availability"><label class="fl">Status Message</label><input type="text" id="f-status_message" placeholder="Status Message"><label class="fl">Timezone</label><input type="text" id="f-timezone" placeholder="Timezone"><label class="fl">Until Time</label><input type="text" id="f-until_time" placeholder="Until Time">
<div style="margin-top:1rem;display:flex;gap:.5rem"><button class="btn btn-p" onclick="save()">Save</button><button class="btn" style="color:var(--cm);border-color:var(--bg3)" onclick="hideModal()">Cancel</button></div></div></div>
<script>
const API="/api/team_members";let editId=null,timer=null,curFilter="";

function showModal(id){editId=id||null;document.getElementById("mt").textContent=id?"Edit":"New";if(id){fetch(API+"/"+id).then(r=>r.json()).then(e=>{document.getElementById("f-name").value=e.name||"";document.getElementById("f-email").value=e.email||"";document.getElementById("f-role").value=e.role||"";document.getElementById("f-availability").value=e.availability||"";document.getElementById("f-status_message").value=e.status_message||"";document.getElementById("f-timezone").value=e.timezone||"";document.getElementById("f-until_time").value=e.until_time||"";})}else{document.getElementById("f-name").value="";document.getElementById("f-email").value="";document.getElementById("f-role").value="";document.getElementById("f-availability").value="";document.getElementById("f-status_message").value="";document.getElementById("f-timezone").value="";document.getElementById("f-until_time").value=""}document.getElementById("modal").style.display="flex"}
function hideModal(){document.getElementById("modal").style.display="none";editId=null}
function debounceSearch(){clearTimeout(timer);timer=setTimeout(load,300)}
function filterBy(v){curFilter=v;load()}
async function loadStats(){const r=await fetch("/api/stats");const d=await r.json();const el=document.getElementById("stats");let h='<div class="stat"><div class="stat-n">'+d.total+'</div><div class="stat-l">Total</div></div>';if(d.by_status){for(const[k,v]of Object.entries(d.by_status)){h+='<div class="stat"><div class="stat-n" style="color:'+stc(k)+'">'+v+'</div><div class="stat-l">'+k.replace(/_/g," ")+'</div></div>'}};el.innerHTML=h}
async function load(){let url=API;const q=document.getElementById("search").value;const p=[];if(q)p.push("q="+encodeURIComponent(q));if(curFilter)p.push("status="+curFilter);if(p.length)url+="?"+p.join("&");const r=await fetch(url);const d=await r.json();const items=d.team_members||[];const el=document.getElementById("list");if(!items.length){el.innerHTML='<div class="empty">No team_members yet</div>';loadStats();return}
el.innerHTML=items.map(e=>{return '<div class="item" ondblclick="showModal(\''+e.id+'\')"><span class="del" onclick="event.stopPropagation();del(\''+e.id+'\')">x</span><h3>'+e.name+'</h3><div class="item-meta"><span>${e.email||"\u2014"}</span><span>${e.role||"\u2014"}</span><span>${e.availability||"\u2014"}</span><span>${e.status_message||"\u2014"}</span></div></div>'}).join("");loadStats()}
async function save(){const body={"name":document.getElementById("f-name").value,"email":document.getElementById("f-email").value,"role":document.getElementById("f-role").value,"availability":document.getElementById("f-availability").value,"status_message":document.getElementById("f-status_message").value,"timezone":document.getElementById("f-timezone").value,"until_time":document.getElementById("f-until_time").value};const method=editId?"PUT":"POST";const url=editId?API+"/"+editId:API;await fetch(url,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});hideModal();load()}
async function del(id){await fetch(API+"/"+id,{method:"DELETE"});load()}
load();loadStats()
</script></body></html>`
